"""add log hooks

Revision ID: 44f08398ec4f
Revises: a11ecb86ab85
Create Date: 2022-06-24 13:28:16.597711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f08398ec4f'
down_revision = 'a11ecb86ab85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_hooks',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('webhook', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('server_id', name=op.f('pk_log_hooks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_hooks')
    # ### end Alembic commands ###
