"""Add bridges

Revision ID: a11ecb86ab85
Revises: ee5fa059dbc1
Create Date: 2022-02-10 22:36:47.999426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11ecb86ab85'
down_revision = 'ee5fa059dbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridges',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('webhook', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name', 'channel_id', name=op.f('pk_bridges'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bridges')
    # ### end Alembic commands ###
