"""initial

Revision ID: abe0e2d9cc02
Revises: 
Create Date: 2021-11-11 00:47:10.140404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe0e2d9cc02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoreplies',
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('partial', sa.Boolean(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('trigger', 'server_id', name=op.f('pk_autoreplies'))
    )
    op.create_table('autoroles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('role_id', 'server_id', name=op.f('pk_autoroles'))
    )
    op.create_table('role_aliases',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('role_id', 'server_id', 'alias', name=op.f('pk_role_aliases'))
    )
    op.create_table('self_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('role_id', 'server_id', name=op.f('pk_self_roles'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('self_roles')
    op.drop_table('role_aliases')
    op.drop_table('autoroles')
    op.drop_table('autoreplies')
    # ### end Alembic commands ###
