"""

Revision ID: aca8f7a94bcc
Revises: b682733b327f
Create Date: 2024-05-15 02:36:03.883004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca8f7a94bcc'
down_revision = 'b682733b327f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoreacts',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('react', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('server_id', 'channel_id', 'react', name=op.f('pk_autoreacts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autoreacts')
    # ### end Alembic commands ###
