"""add lookup words for autoreact feature

Revision ID: ea08fb420d96
Revises: 0b579352511c
Create Date: 2024-12-25 01:50:27.352841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea08fb420d96'
down_revision = '0b579352511c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autoreacts', schema=None) as batch_op:
        batch_op.drop_constraint("pk_autoreacts")
        batch_op.add_column(sa.Column('lookup', sa.String(), nullable=False))
        batch_op.create_primary_key("pk_autoreacts", ["server_id", "channel_id", "react", "lookup"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autoreacts', schema=None) as batch_op:
        batch_op.drop_constraint("pk_autoreacts")
        batch_op.drop_column('lookup')
        batch_op.create_primary_key("pk_autoreacts", ["server_id", "channel_id", "react"])

    # ### end Alembic commands ###
